server:
  port: 8000
spring:
  application:
    name: microservice-simple-provider-user-trace
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: create
    # 配置mysql数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.springframework.web.servlet.DispatcherServlet: DEBUG

## INFO
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
management:
  security:
    enabled: false

