server:
  port: 8000
spring:
  application:
    name: microservice-provider-user-ip
  cloud:
    inetutils:
      ignored-interfaces:
        - docker0
        - veth.*
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: create
      # \u914D\u7F6Emysql\u6570\u636E\u6E90
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123

logging:                                # \u914D\u7F6E\u65E5\u5FD7\u7EA7\u522B\uFF0C\u8BA9hibernate\u6253\u5370\u51FA\u6267\u884C\u7684SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.springframework.cloud.commons.util.InetUtils: TRACE   # \u5F00\u542F\u8FD9\u8FB9\u7684\u65E5\u5FD7\uFF0C\u53EF\u4EE5\u6253\u5370\u51FASpring\u67E5\u627E\u7F51\u5361\u7684\u8FC7\u7A0B

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true