server:
  port: 8762

eureka:
  client:
  # 是否将自己注册到Eureka Server上
    register-with-eureka: false
    # 是否从Eureka Server获取注册信息
    fetch-registry: false
    # 设置与Eureka Server的交互地址，多个地址间可以用逗号隔开
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/,http://localhost:8761/hehe/
  instance:
  # 将自己的IP注册到Eureka Server
    prefer-ip-address: true

spring:
  application:
    name: microservice-consumer-user