server:
  port: 8000
spring:
  application:
    name: microservice-provider-user-zipkin
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: create
    # \u914D\u7F6Emysql\u6570\u636E\u6E90
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  zipkin:
    # microservice-trace-zipkin-server-eureka \u540D\u79F0\u4E3A\u5176\u5DE5\u7A0B\u7684spring.application.name\u503C
    base-url: http://microservice-trace-zipkin-server-eureka/
  sleuth:
    sampler:
      percentage: 1.0

logging:                                # \u914D\u7F6E\u65E5\u5FD7\u7EA7\u522B\uFF0C\u8BA9hibernate\u6253\u5370\u51FA\u6267\u884C\u7684SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true