server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie-feign-hystrix-fallback-factory
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level: debug

# \u8BF4\u660E\uFF1A\u8BF7\u52A1\u5FC5\u6CE8\u610F\uFF0C\u4ECESpring Cloud Dalston\u5F00\u59CB\uFF0CFeign\u9ED8\u8BA4\u662F\u4E0D\u5F00\u542FHystrix\u7684\u3002
# \u56E0\u6B64\uFF0C\u5982\u4F7F\u7528Dalston\u8BF7\u52A1\u5FC5\u989D\u5916\u8BBE\u7F6E\u5C5E\u6027\uFF1Afeign.hystrix.enabled=true\uFF0C\u5426\u5219\u65AD\u8DEF\u5668\u4E0D\u4F1A\u751F\u6548\u3002
# \u800C\uFF0CSpring Cloud Angel/Brixton/Camden\u4E2D\uFF0CFeign\u9ED8\u8BA4\u90FD\u662F\u5F00\u542FHystrix\u7684\u3002\u65E0\u9700\u8BBE\u7F6E\u8BE5\u5C5E\u6027\u3002
feign:
  hystrix:
    enabled: true
