server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie-feign-manual
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true