server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xinjump/spring-cloud-config-repo      # \u914D\u7F6EGit\u4ED3\u5E93\u7684\u5730\u5740
          username:                                                         # Git\u4ED3\u5E93\u7684\u8D26\u53F7
          password:                                                         # Git\u4ED3\u5E93\u7684\u5BC6\u7801
security:
  basic:
    enabled: true               # \u5F00\u542F\u57FA\u4E8EHTTP basic\u7684\u8BA4\u8BC1
  user:
    name: user                  # \u914D\u7F6E\u767B\u5F55\u7684\u8D26\u53F7\u662Fuser
    password: password123       # \u914D\u7F6E\u767B\u5F55\u7684\u5BC6\u7801\u662Fpassword123