server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie-feign-logging
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
# \u914D\u7F6EFeign\u65E5\u5FD7\u7EA7\u522B
feign:
  client:
    config:
      microservice-provider-user:
        loggingLevel: full

logging:
  level:
    # \u5C06Feign\u63A5\u53E3\u7684\u65E5\u5FD7\u7EA7\u522B\u8BBE\u7F6E\u6210DEBUG\uFF0C\u56E0\u4E3AFeign\u7684Logger.Level\u53EA\u5BF9DEBUG\u4F5C\u51FA\u54CD\u5E94\u3002
    com.xin.jump.feign.UserFeignClient: DEBUG
